added image editing with filerobot
DSGT-DLP/Deep-Learning-Playground pull request #542
Opened 2023-01-23 02:28 UTC by Dashrekker

![image](https://user-images.githubusercontent.com/47958374/213956296-fa896c61-a297-4b9f-96bd-2908188f27e5.png)

Added image editor to object detection using filerobot. Allows user to implement social media esque image edits.

2023-01-23 02:42 UTC, karkir0003 commented on frontend/playground-frontend/src/components/ObjectDetection/ObjectDetection.js
> +    const arr = dataurl.split(",");
where did you get this code from? @Dashrekker

2023-01-23 02:42 UTC, karkir0003 commented on frontend/playground-frontend/src/components/ObjectDetection/ObjectDetection.js
> +              // icon: CropClassicTv, // optional, CropClassicTv is a React Function component. Possible (React Function component, string or HTML Element)
dead code?

2023-01-23 02:43 UTC, karkir0003 requested changes
minor questions/clarifications. overall looking good to me :)

Wait for Faris' comments

2023-01-23 03:24 UTC, karkir0003 commented
@Dashrekker I conditionally approve your PR. Wait on Faris' comments :)

2023-01-23 03:30 UTC, karkir0003 reviewed
address faris' comments

2023-01-24 01:07 UTC, farisdurrani commented on frontend/playground-frontend/src/components/general/ImageFileUpload.js
> +    console.log(e.target.files[0] ? e.target.files[0] : null);
Any reason this console log is here?

2023-01-24 01:11 UTC, karkir0003 commented on frontend/playground-frontend/src/components/general/ImageFileUpload.js
> +    console.log(e.target.files[0] ? e.target.files[0] : null);
@Dashrekker

2023-01-24 01:21 UTC, Dashrekker commented on frontend/playground-frontend/src/components/general/ImageFileUpload.js
> +    console.log(e.target.files[0] ? e.target.files[0] : null);
It's for debugging. I can remove it.

2023-01-24 01:37 UTC, Dashrekker commented on frontend/playground-frontend/src/components/general/ImageFileUpload.js
> +    console.log(e.target.files[0] ? e.target.files[0] : null);
Just removed it.

2023-01-24 03:06 UTC, karkir0003 commented
@Dashrekker do a `git pull origin dev` followed by a `git push` to make sure this branch is up to date with latest version of `dev`

2023-01-24 03:07 UTC, karkir0003 reviewed
update this branch by doing `git pull origin dev`

2023-01-24 03:27 UTC, karkir0003 reviewed
do we need the `plain-white-background.jpg` file @Dashrekker

2023-01-24 03:37 UTC, karkir0003 approved these changes
approve as long as the build checks pass

2023-01-24 03:37 UTC, farisdurrani approved these changes

2023-01-24 03:48 UTC, merged