Upgrade csv
DSGT-DLP/Deep-Learning-Playground pull request #543
Opened 2023-01-23 04:46 UTC by mateo0203

test

2023-01-23 22:51 UTC, farisdurrani approved these changes

2023-01-23 23:06 UTC, farisdurrani commented
All good for me. Just fix the conflicts and I recommend waiting for Karthik's approval

2023-01-24 00:40 UTC, karkir0003 commented
wait a sec. i dont think mateo finished this task

2023-01-24 00:46 UTC, karkir0003 requested changes
lmk when you have this feature ready

2023-01-24 01:06 UTC, karkir0003 commented on frontend/playground-frontend/src/components/Home/CSVInputFile.js
> +
@mateo0203 lmk when you resolved the blocker with daniel

2023-01-24 01:06 UTC, karkir0003 requested changes
wait on mateo to resolve blocker with daniel

2023-01-28 03:52 UTC, farisdurrani commented
Closing since issue is resolved in #552 using this PR's code

2023-01-28 03:52 UTC, closed without merging