Initial typescript refactor
DSGT-DLP/Deep-Learning-Playground pull request #649
Opened 2023-03-17 01:49 UTC by dwu359

Setup typescript and typescript-eslint configurations and converted App.tsx to typescript

2023-03-17 02:01 UTC, farisdurrani commented
PR will not be approved until certain files are reverted, to make this PR simpler

2023-03-17 02:04 UTC, karkir0003 commented
@farisdurrani build checks failing. Do we need to modify for TS?

2023-03-17 02:05 UTC, karkir0003 commented on frontend/playground-frontend/.eslintrc.json
Are you sure this will use the latest eslint standard. Also, I think what would be useful is if devs setup eslint detection in vscode so that they can automatically correct eslint errors or disable where needed @farisdurrani

2023-03-17 02:05 UTC, karkir0003 commented on frontend/playground-frontend/package.json
> +    "@testing-library/react": "^13.4.0",
nice we are using this library. at my work, we are migrating our JS unit tests to RTL from enzyme

2023-03-17 02:06 UTC, karkir0003 commented on frontend/playground-frontend/src/Home.tsx
> +      {/* {beginnerMode ? null : (
why this commented out code?

2023-03-17 02:06 UTC, karkir0003 commented on frontend/playground-frontend/src/Home.tsx
> +          {/* <CSVInputFile2 /> */}
same idea here

2023-03-17 02:06 UTC, karkir0003 commented on frontend/playground-frontend/src/components/Home/CSVInputFile.tsx
> +  const dispatch = useDispatch();
why this commented out code?

2023-03-17 02:07 UTC, karkir0003 requested changes
see comments. @farisdurrani, I'm placing a lot of trust in this important PR and believe in you 🙏

2023-03-17 02:14 UTC, farisdurrani commented
TODO @dwu359 restore old eslint rules

2023-03-17 02:39 UTC, farisdurrani commented
This PR is not approved until major fixes are made to installing typescript

2023-03-17 16:26 UTC, dwu359 commented
If I do npm install --legacy-peer-deps, it works: [https://stackoverflow.com/questions/66239691/what-does-npm-install-legacy-peer-deps-do-exactly-when-is-it-recommended-wh](https://stackoverflow.com/questions/66239691/what-does-npm-install-legacy-peer-deps-do-exactly-when-is-it-recommended-wh)

The problem is caused by some npm peer dependency conflict between react-scripts and typescript for some reason

2023-03-18 17:15 UTC, farisdurrani approved these changes

2023-03-18 17:15 UTC, karkir0003 approved these changes

2023-03-18 17:16 UTC, merged