Added Phone Number and Email Inputs to Tabular Review
DSGT-DLP/Deep-Learning-Playground pull request #756
Opened 2023-05-16 02:12 UTC by Dashrekker

2023-05-18 02:46 UTC, karkir0003 commented
@Dashrekker status on this PR? Any blockers?

2023-05-19 19:16 UTC, Dashrekker commented
@karkir0003 I've updated the description so you can see what it looks like and what is being updated to the backend.

2023-05-19 21:19 UTC, karkir0003 commented
hey @, can u have @farisdurrani or @dwu359 review

2023-05-20 19:01 UTC, farisdurrani approved these changes

2023-05-20 19:01 UTC, farisdurrani commented
Approved subject to Daniel's approval. Please update your branch

2023-05-20 22:36 UTC, karkir0003 commented
@farisdurrani updated pr to not be in draft status

2023-05-21 16:17 UTC, karkir0003 commented on frontend/playground-frontend/src/features/Train/features/Tabular/components/TabularReviewStep.tsx
> +          <TextField label="Phone Number" onChange={onChange} />
@Dashrekker do you have any validation mechanisms in place to ensure that a phone number that's entered is valid? Similar thing for email? Might be good to validate this before submitting training request

2023-05-21 16:17 UTC, karkir0003 requested changes
validation mechanisms for phone number and email?

@farisdurrani thoughts?

@Dashrekker

2023-05-22 11:32 UTC, karkir0003 commented
@Dashrekker can u show me screen recording of error made in phone number? if users enter invalid email or phone number, we should not let them make train request

thoughts @farisdurrani @dwu359

2023-05-22 19:33 UTC, Dashrekker commented
@karkir0003 I added a video of email and phone number validation to the description.

2023-05-22 20:03 UTC, karkir0003 approved these changes

2023-05-22 20:03 UTC, karkir0003 commented
looks good @. i think u are safe to merge

@farisdurrani confirm?

2023-05-22 22:24 UTC, farisdurrani commented
Yes! Go ahead and merge @Dashrekker

2023-05-22 22:25 UTC, merged