issue #749 - implement image training flow
DSGT-DLP/Deep-Learning-Playground pull request #782
Opened 2023-05-29 03:23 UTC by AmyCGT

2023-05-29 03:25 UTC, AmyCGT commented
https://github.com/DSGT-DLP/Deep-Learning-Playground/issues/749 <- the issue

2023-05-29 03:30 UTC, karkir0003 commented
@AmyCGT put a screen recording of the flow

2023-05-29 03:37 UTC, karkir0003 requested changes
address comments

@farisdurrani @dwu359 provide your inputs as well

2023-05-29 03:37 UTC, karkir0003 commented on frontend/playground-frontend/src/features/Train/features/Image/components/ImageDatasetStep.tsx
> +              acceptedTypes={".zip"}
did u validate that only .zip files are accepted when you upload image data in image trainspace? @AmyCGT

2023-05-29 03:37 UTC, karkir0003 commented on frontend/playground-frontend/src/settings.tsx
> +      //   parameter_name: "(H, W)",
is this needed? @AmyCGT 

i see commented out code

2023-05-29 03:37 UTC, karkir0003 commented on frontend/playground-frontend/src/settings.tsx
> +      //   parameter_name: "(H, W)",
same nit here

2023-05-31 00:39 UTC, farisdurrani commented
Hey @AmyCGT can you please fix the conflicts? I did not realize your PR had conflicts with the nextjs branch before I merged in the Remove playground-frontend PR

2023-05-31 00:40 UTC, farisdurrani commented
The conflicts seem bad so I recommend making a copy of all the files you change, pull in the latest nextjs branch, and paste in back your changes

2023-05-31 12:59 UTC, dwu359 reviewed
<img width="1048" alt="image" src="https://github.com/DSGT-DLP/Deep-Learning-Playground/assets/54150946/11df44ff-f7e0-4cf8-b21a-2c6c3cbf97f1">
Any way to make the inputs for Conv2d wrap around to the bottom btw?

2023-05-31 13:02 UTC, dwu359 reviewed
<img width="673" alt="image" src="https://github.com/DSGT-DLP/Deep-Learning-Playground/assets/54150946/d08c2b07-5e97-472c-bd36-b0a17c8dffec">
This is what shows up for me in review step btw, we're still deciding how the review step information should be displayed, but rn also display data from parameters in review step for testing purposes

2023-05-31 16:52 UTC, AmyCGT commented
video preview

https://github.com/DSGT-DLP/Deep-Learning-Playground/assets/104514492/56b9d4a9-d180-4c3b-908f-c246b5ae38aa

2023-06-01 01:09 UTC, karkir0003 commented
@dwu359 please refer to Amy's updated PR #787 for her latest changes

2023-06-01 01:09 UTC, karkir0003 commented
closing this PR since this is old version

2023-06-01 01:09 UTC, closed without merging