Adding Unit Tests for dl_eval.py
DSGT-DLP/Deep-Learning-Playground pull request #854
Opened 2023-07-07 16:33 UTC by yeaitsurya

This pull request introduces unit tests for the compute_correct and compute_accuracy functions. These tests utilize the pytest framework and incorporate "dummy tensors" to simulate various input conditions.

# Adding Unit Tests for compute_correct and compute_accuracy Functions in dl_eval.py

**What user problem are we solving?**

The current lack of unit tests for the compute_correct and compute_accuracy functions in dl_eval.py presents a potential risk of undetected bugs or errors. By addressing this issue, we aim to ensure the accuracy and reliability of these functions, leading to improved overall code quality and performance.

**What solution does this PR provide?**

This pull request introduces unit tests for the compute_correct and compute_accuracy functions. These tests utilize the pytest framework and incorporate "dummy tensors" to simulate various input conditions. By evaluating different scenarios and edge cases, we can confidently assert the correctness of the functions and identify any potential issues.

**Testing Methodology**
How did you test your changes and verify that existing 
functionality is not broken

During the testing process, I executed the unit tests from the command line interface and verified that all test cases passed without any failures or errors. This confirms the correctness of the `compute_correct` and `compute_accuracy` functions in `dl_eval.py`.

**Any other considerations**
N/A

2023-07-07 16:36 UTC, karkir0003 requested changes
add extra ubit tests to handle other edge cases

2023-07-07 16:36 UTC, karkir0003 commented on tests/test_dl_eval.py
> +
have a test case to verify case of 0 accuracy, maybe some accuracy between 0 and 1 just to verify that the calculation is correct. @yeaitsurya

2023-07-07 19:35 UTC, karkir0003 requested changes
parametrized testing please

2023-07-07 19:35 UTC, karkir0003 commented on tests/test_dl_eval.py
> +    )
try using parametrized testing to test different cases 

see these docs: https://www.tutorialspoint.com/pytest/pytest_parameterizing_tests.htm

2023-07-08 00:48 UTC, yeaitsurya commented
> parametrized testing please

@karkir0003 just commited new changes implementing this.

2023-07-08 02:33 UTC, karkir0003 approved these changes

2023-07-08 02:34 UTC, merged