Logo Functionality Changes
DSGT-DLP/Deep-Learning-Playground pull request #905
Opened 2023-08-16 19:54 UTC by prishavall

# Logo Functionality Changes

**What user problem are we solving?**
Previously, hover functionality on the DLP logo on the very top left in the Nav Bar doesn't work since the nextjs Image component doesn't really work too well with Bootstrap components. 
**What solution does this PR provide?**
The logo should changes color in the same way as the link next to it as you hover.
**Testing Methodology**
How did you test your changes and verify that existing 
functionality is not broken
Ran local host and hovered/clicked to see functionality
**Any other considerations**

2023-08-16 19:54 UTC, karkir0003 commented
@farisdurrani

2023-08-16 19:54 UTC, karkir0003 commented
@prishavall can u post a brief video/screen recording?

2023-08-19 16:32 UTC, farisdurrani approved these changes

2023-08-19 16:33 UTC, farisdurrani commented
Removed some commented code. @prishavall please resolve the conflicts and you can merge it in.

Note: the changes in .aws/task-definition.json are purely Prettier

2023-08-19 16:33 UTC, farisdurrani commented
Good job

2023-08-30 02:21 UTC, farisdurrani commented
Hey @prishavall can you solve the conflicts and merge this?

2023-09-03 03:27 UTC, karkir0003 commented on frontend/src/common/components/NavBarMain.tsx
> +=======
remove this @prishavall

2023-09-03 03:27 UTC, karkir0003 commented on frontend/src/common/components/NavBarMain.tsx
> +=======
remove this @prishavall

2023-09-03 03:28 UTC, karkir0003 requested changes
@prishavall minor fixes. see my comments

2023-09-03 03:37 UTC, karkir0003 commented on frontend/src/common/components/NavBarMain.tsx
> +                        <Link href="/learn-mod" id="basic-nav-dropdown">
You mean `<Link href="/learn-mod" id="basic-nav-dropdown"/>`

2023-09-03 03:37 UTC, karkir0003 requested changes
see comment on closing tag

2023-09-03 03:52 UTC, karkir0003 approved these changes

2023-09-03 03:53 UTC, merged